logging:
  file:
    name: /home/kidusmt/Documents/CS590-SA/elk-linux/spring-boot-elk2.log

server:
  port: 8095

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shoppingcartcommand
  application:
    name: ShoppingCartCommandService
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: project.swa.ShoppingCartCommandService.service

app:
  topic:
    shoppingcarttopic: shoppingcarttopic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/